# Generated by Django 2.0.6 on 2018-06-24 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0002_increase_phone_length_in_organizations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='address',
            field=models.CharField(max_length=75, unique=True),
        ),
    ]
