# Generated by Django 2.0.6 on 2018-06-25 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0003_increase_address_length_in_buidlings'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['building'], name='directory_o_buildin_1232fd_idx'),
        ),
    ]
